name: End-to-end tests

on:
  push:

jobs:
  cypress-run:
    runs-on: ubuntu-22.04

    env:
      BASE_URL: ${{ secrets.BASE_URL }}
      CYPRESS_USERNAME: ${{ secrets.CYPRESS_USERNAME }}
      CYPRESS_PASSWORD: ${{ secrets.CYPRESS_PASSWORD }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Criar pastas de relatório
        run: |
          mkdir -p cypress/reports/junit

      - name: Cypress run
        uses: cypress-io/github-action@v6

      - name: Upload relatório JUnit
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: cypress-junit-report
          path: cypress/reports/junit
