name: End-to-end tests
on: push
jobs:
  cypress-run:
    runs-on: ubuntu-22.04
     env:
      # 🔐 Secrets definidos no repositório
      BASE_URL: ${{ secrets.BASE_URL }}
      CYPRESS_USERNAME: ${{ secrets.CYPRESS_USERNAME }}
      CYPRESS_PASSWORD: ${{ secrets.CYPRESS_PASSWORD }}
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Cypress run
      uses: cypress-io/github-action@v6